# Generated by Django 6.0.2 on 2026-02-18 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Veřejná fotka'),
        ),
        migrations.AddField(
            model_name='photo',
            name='tagged_people',
            field=models.ManyToManyField(blank=True, related_name='photos_of_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
