# Generated by Django 6.0.2 on 2026-02-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0002_photo_is_public_photo_tagged_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='category',
            field=models.CharField(choices=[('nature', '🌲 Příroda a krajina'), ('architecture', '🏰 Architektura a města'), ('animals', '🐾 Zvířata'), ('people', '❤️ Lidé a momentky'), ('fun', '🍻 Zábava a relax')], default='nature', max_length=20, verbose_name='Kategorie'),
        ),
    ]
