# Generated by Django 6.0.2 on 2026-03-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0003_photo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.CharField(blank=True, help_text='AI or manual tags separated by comma', max_length=255),
        ),
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(choices=[('nature', '🌲 Nature'), ('architecture', '🏰 Architecture'), ('animals', '🐾 Animals'), ('people', '❤️ People'), ('fun', '🍻 Fun')], default='nature', max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Public Photo'),
        ),
    ]
