# Generated by Django 6.0.2 on 2026-03-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0005_album_photo_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(max_length=255, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
