"""
Django settings for skotsko_mapa project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

load_dotenv()  # Load variables from .env file (if present)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'development-fallback-secret-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['*']  # For Fly.io and testing we temporarily allow all hosts

CSRF_TRUSTED_ORIGINS = [
    'https://my-scottish-gallery.fly.dev',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    'cloudinary',
    'galerie',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'skotsko_mapa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'skotsko_mapa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# First, check whether Fly.io provided a secret URL for the production database
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    # 1. RUNNING IN THE CLOUD (Fly.io production)
    DATABASES = {
        'default': dj_database_url.config(default=DATABASE_URL, conn_max_age=600)
    }
else:
    # 2. RUNNING LOCALLY ON YOUR MACHINE (local development)
    # Please fill in the values you previously used here.
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'mapagalerie',  # e.g. mapa_db or my_project
            'USER': 'postgres',     # Your PostgreSQL user (often postgres)
            'PASSWORD': '12345',    # Your database password
            'HOST': 'localhost',
            'PORT': '5432',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Directory where static files are collected in production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# New STORAGES format for Django 5.1+ and 6.0
STORAGES = {
    "default": {
        # Default file storage for photos (local) – used when .env is not configured
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        # Serve and compress CSS/JS through WhiteNoise
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# If a Cloudinary key is available from .env, override default storage for photos
if os.environ.get('CLOUDINARY_URL'):
    STORAGES["default"]["BACKEND"] = "cloudinary_storage.storage.MediaCloudinaryStorage"

# Media files (uploaded images, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



# Redirects after login and logout
LOGIN_REDIRECT_URL = 'galerie:photo_list'
LOGOUT_REDIRECT_URL = 'galerie:photo_list'

# ==========================================
# BEZPEČNOSTNÍ ŠTÍTY PRO PRODUKCI (Fly.io)
# ==========================================
# Tyto štíty se aktivují POUZE, když je DEBUG = False (tedy na ostrém serveru).
# Na lokálu (DEBUG = True) zůstanou vypnuté, aby se vám dobře vyvíjelo.

if not DEBUG:
    # 1. Řekne Djangu, že šifrování (HTTPS) obstarává Fly.io před ním
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # 2. Vynutí, aby se úplně každý přesměroval z nezabezpečeného HTTP na bezpečné HTTPS
    SECURE_SSL_REDIRECT = True
    
    # 3. Přihlašovací cookies budou cestovat jen přes šifrované spojení (nelze je ukrást na veřejné Wi-Fi)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # 4. Zakáže vložení vašeho webu do cizí stránky (ochrana proti Clickjackingu)
    X_FRAME_OPTIONS = 'DENY'
    
    # 5. Zapne ochranu prohlížeče proti podvrženým skriptům
    SECURE_BROWSER_XSS_FILTER = True